[project]
name = "sample-app"
version = "0.1.0"
description = "sample app"
requires-python = ">=3.14"
dependencies = [
 "pytest-cov>=7.0.0",
 "ruff>=0.14.14",
 "ty>=0.0.14",
]

[dependency-groups]
dev = ["pytest>=9.0.2"]
